baseurl = "https://blist.vercel.app"
metaDataFormat = "yaml"
title = "Blist Multilingual Theme"
theme = "blist"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
themesDir = "themes"
baseURL = ""
publishDir = "public"

[languages.en]
contentDir = "content/en"
weight = 1
languageName = "English"

  [languages.en.params]
  introTitle = "Hey! I'm Katheryn Fox"
  introSubtitle = "26 y/o junior developer who enjoys social card games, blogging and painting"
  introPhoto = "/picture.jpg"

[[languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 1

[[languages.en.menu.main]]
name = "About"
url = "page/about/"
weight = 2

[[languages.en.menu.main]]
name = "Tags"
url = "tags"
weight = 3

[languages.de]
contentDir = "content/de"
weight = 2
languageName = "Deutsch"
title = "Blist (mehrsprachig)"
description = "Modernes Blog-Theme für Ihre Hugo-Site."

  [languages.de.params]
  introTitle = "Hallo, ich bin Katheryn Fox"
  introSubtitle = "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
  introPhoto = "/picture.jpg"

[[languages.de.menu.main]]
name = "Blog"
url = "blog"
weight = 1

[[languages.de.menu.main]]
name = "Über mich"
url = "page/about/"
weight = 2

[[languages.de.menu.main]]
name = "Tags"
url = "tags"
weight = 3

[languages.dy]
contentDir = "content/dy"
weight = 3
languageName = "Test Language"

[params]
darkModeToggle = true
enableSearch = true
copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
favicon = "/favicon.svg"
ascentColor = "bg-blue-100"

[params.homepage.social]
title = "Follow me"
description = "I work on everything coding and tweet developer memes"
twitter = "https://twitter.com/"
linkedin = "https://linkedin.com/in/"
github = "https://github.com/"
medium = "https://medium.com/"
reddit = "https://reddit.com/"
dribbble = "https://dribbble.com/"

[[menu.main]]
name = "About"
url = "/about"

[build]
writeStats = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.highlight]
style = "dracula"

[markup.goldmark.renderer]
unsafe = true
